.TH "Andriod/MerchantActivity/src/app/merchantLocalization/AccountSettingsActivity.java" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Andriod/MerchantActivity/src/app/merchantLocalization/AccountSettingsActivity.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAccountSettingsActivity\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBapp\&.merchantLocalization\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
