.TH "MerchantLocalizationActivity" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MerchantLocalizationActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static final int \fBTIMEOUT_MILLISEC\fP = 3000"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file MerchantLocalizationActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
