.TH "BuildConfig" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BuildConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final boolean \fBDEBUG\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file BuildConfig\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
