.TH "ConnectionDetector" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionDetector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionDetector\fP (Context context)"
.br
.ti -1c
.RI "boolean \fBisConnectingToInternet\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ConnectionDetector\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean isConnectingToInternet ()\fC [inline]\fP"
Checks for all possible internet providers\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean on whether there is an internet connection 
.RE
.PP

.PP
Definition at line 19 of file ConnectionDetector\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
