.TH "Notifications" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Notifications \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBgetData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBNotifications\fP list\&. Pulls subscribed or nearby merchant information from the database\&. Need service-oriented architecture and needs three elements: external database, web-service, mobile web-service client\&. 
.PP
\fBAuthor:\fP
.RS 4
Chihiro 
.RE
.PP

.PP
Definition at line 27 of file Notifications\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void getData ()\fC [inline]\fP"
Connect to web service (database) 
.PP
Definition at line 56 of file Notifications\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
