.TH "MerchantMap" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MerchantMap \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MapActivity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBgetLocation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisRouteDisplayed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MerchantMap\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean isRouteDisplayed ()\fC [inline]\fP, \fC [protected]\fP"
Returns if it is currently displaying the route information\&. 
.PP
Definition at line 42 of file MerchantMap\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
