.TH "CommonUtilities" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonUtilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final String \fBSERVER_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/cloudMessaging/register\&.php'"
.br
.ti -1c
.RI "static final String \fBREGISTRATION_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/cloudMessaging/register\&.php'"
.br
.ti -1c
.RI "static final String \fBUSERNOTIFICATION_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/PHPRetrieveUserNotification\&.php'"
.br
.ti -1c
.RI "static final String \fBUPDATEUSERLOCATION_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/PHPUpdateUserLocation\&.php'"
.br
.ti -1c
.RI "static final String \fBNEARBYMERCHANTS_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/PHPGetNearbyMerchants\&.php'"
.br
.ti -1c
.RI "static final String \fBLOGIN_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/PHPValidateLogin\&.php'"
.br
.ti -1c
.RI "static final String \fBNOTIFICATION_URL\fP = 'http://dana\&.ucc\&.nau\&.edu/~cs854/PHPGetNotifications\&.php'"
.br
.ti -1c
.RI "static final String \fBSENDER_ID\fP = '901660126123'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file CommonUtilities\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
