.TH "RestClient" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RestClient \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static String \fBgetASCIIContentFromEntity\fP (HttpEntity entity)  throws IllegalStateException, IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file RestClient\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
