.TH "Customers" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Customers \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBgetData\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Customerlist\&. Pulls subscribed or nearby customer names from the database\&. Need service-oriented architecture and needs three elements: external database, web-service, mobile web-service client\&. 
.PP
\fBAuthor:\fP
.RS 4
Chihiro
.RE
.PP
Notes: For connection to work, Apache server must be handled to start PHP\&. Also, make sure NAU Wi-Fi is connected on the device\&.
.PP
IP address changes for each Wi-Fi access! 
.PP
Definition at line 68 of file Customers\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void getData ()\fC [inline]\fP"
Connect to webservice (database) 
.PP
Definition at line 95 of file Customers\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
