.TH "Coupons" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coupons \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBgetData\fP ()"
.br
.ti -1c
.RI "void \fBgetCoupons\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Coupons\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void getData ()\fC [inline]\fP"
Connect to webservice (database) 
.PP
Definition at line 54 of file Coupons\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
