.TH "WakeLocker" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WakeLocker \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBacquire\fP (Context context)"
.br
.ti -1c
.RI "static void \fBrelease\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file WakeLocker\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
