.TH "AppDelegate" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject, <UIApplicationDelegate>, UIResponder, and <UIApplicationDelegate>\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMapViewController\fP * \fBviewController\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIWindow * \fBwindow\fP"
.br
.ti -1c
.RI "IBOutlet UIWindow * \fBwindow\fP"
.br
.ti -1c
.RI "IBOutlet \fBMapViewController\fP * \fBviewController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file AppDelegate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
