.TH "Website Directory Reference" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcloudMessaging\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatabaseConfig\&.php\fP"
.br
.ti -1c
.RI "file \fBdbValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMaccountSettings\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMcreateNewAccount\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMcreateNewAccountValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMcurrentLocation\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMhomePage\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMlogin\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMloginValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMlogOut\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMmerchantMap\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMmerchantSettings\&.php\fP"
.br
.ti -1c
.RI "file \fBMCMrecentActivities\&.php\fP"
.br
.ti -1c
.RI "file \fBmenuFunction\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPGetCoupons\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPGetNearbyCustomers\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPGetNearbyMerchants\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPGetUserTransactions\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPPut\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPQuery\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPRetrieveUserNotification\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPToggleCustomerNotification\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPUpdateUserLocation\&.php\fP"
.br
.ti -1c
.RI "file \fBPHPValidateLogin\&.php\fP"
.br
.in -1c
