.TH "Andriod/LocalizationActivity/src/app/localization Directory Reference" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Andriod/LocalizationActivity/src/app/localization Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCoupons\&.java\fP"
.br
.ti -1c
.RI "file \fBHomeActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBLocalizationActivity\&.java\fP"
.br
.ti -1c
.RI "file \fBMerchantMap\&.java\fP"
.br
.ti -1c
.RI "file \fBMerchantMapItemOverlay\&.java\fP"
.br
.ti -1c
.RI "file \fBMerchants\&.java\fP"
.br
.ti -1c
.RI "file \fBNotifications\&.java\fP"
.br
.ti -1c
.RI "file \fBRegisterActivity\&.java\fP"
.br
.in -1c
