.TH "Andriod/LocalizationActivity/src/app/utilities Directory Reference" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Andriod/LocalizationActivity/src/app/utilities Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAlertDialogManager\&.java\fP"
.br
.ti -1c
.RI "file \fBCommonUtilities\&.java\fP"
.br
.ti -1c
.RI "file \fBConnectionDetector\&.java\fP"
.br
.ti -1c
.RI "file \fBCustomDialog\&.java\fP"
.br
.ti -1c
.RI "file \fBGCMIntentService\&.java\fP"
.br
.ti -1c
.RI "file \fBRestClient\&.java\fP"
.br
.ti -1c
.RI "file \fBServerUtilities\&.java\fP"
.br
.ti -1c
.RI "file \fBWakeLocker\&.java\fP"
.br
.in -1c
