.TH "Website/cloudMessaging Directory Reference" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/cloudMessaging Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.php\fP"
.br
.ti -1c
.RI "file \fBdb_connect\&.php\fP"
.br
.ti -1c
.RI "file \fBdb_functions\&.php\fP"
.br
.ti -1c
.RI "file \fBGCM\&.php\fP"
.br
.ti -1c
.RI "file \fBindex\&.php\fP"
.br
.ti -1c
.RI "file \fBregister\&.php\fP"
.br
.ti -1c
.RI "file \fBsend_message\&.php\fP"
.br
.ti -1c
.RI "file \fBtest\&.php\fP"
.br
.in -1c
