.TH "Andriod/Merchant/gen/app/merchantLocalization Directory Reference" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Andriod/Merchant/gen/app/merchantLocalization Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuildConfig\&.java\fP"
.br
.ti -1c
.RI "file \fBR\&.java\fP"
.br
.in -1c
