.TH "iPhone/Capstone App/Capstone AppTests/Capstone_AppTests.h" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iPhone/Capstone App/Capstone AppTests/Capstone_AppTests.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <SenTestingKit/SenTestingKit\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCapstone_AppTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
