.TH "Capstone_AppTests" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Capstone_AppTests \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SenTestCase\&.
.SH "Detailed Description"
.PP 
Definition at line 11 of file Capstone_AppTests\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
