.TH "MapViewCompassDemo" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapViewCompassDemo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MapActivity\&.
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSmoothCanvas\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonStop\fP ()"
.br
.ti -1c
.RI "boolean \fBisRouteDisplayed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Example of how to use an \fBcom\&.google\&.android\&.maps\&.MapView\fP in conjunction with the \fBcom\&.hardware\&.SensorManager\fP 
.SS "\fBMapViewCompassDemo\fP"
.PP
This demonstrates creating a Map based Activity\&.
.PP
.SS "Source files"
.PP
src/com\&.example\&.android\&.apis/view/MapViewCompassDemo\&.java The Alert Dialog Samples implementation  
.PP
Definition at line 61 of file MapViewCompassDemo\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
