.TH "MapViewDemo" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapViewDemo \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MapActivity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBisRouteDisplayed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Example of how to use an \fBcom\&.google\&.android\&.maps\&.MapView\fP\&. 
.SS "\fBMapViewDemo\fP"
.PP
This demonstrates creating a Map based Activity\&.
.PP
.SS "Demo"
.PP
Views/MapView
.PP
.SS "Source files"
.PP
src/com\&.example\&.android\&.apis/view/MapViewDemo\&.java The Alert Dialog Samples implementation  /res/layout/mapview\&.xml Defines contents of the screen  
.PP
Definition at line 45 of file MapViewDemo\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
