.TH "AlertDialogManager" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlertDialogManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshowAlertDialog\fP (Context context, String title, String message, Boolean status)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file AlertDialogManager\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void showAlertDialog (Contextcontext, Stringtitle, Stringmessage, Booleanstatus)\fC [inline]\fP"
Function to display simple Alert Dialog 
.PP
\fBParameters:\fP
.RS 4
\fIcontext\fP - application context 
.br
\fItitle\fP - alert dialog title 
.br
\fImessage\fP - alert message 
.br
\fIstatus\fP - success/failure (used to set icon)
.IP "\(bu" 2
pass null if you don't want icon 
.PP
.RE
.PP

.PP
Definition at line 16 of file AlertDialogManager\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
