.TH "Website/cloudMessaging/config.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/cloudMessaging/config.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBDB_HOST\fP 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.ti -1c
.RI "const \fBDB_USER\fP 'kd268'"
.br
.ti -1c
.RI "const \fBDB_PASSWORD\fP 'capstone'"
.br
.ti -1c
.RI "const \fBDB_DATABASE\fP 'kd268'"
.br
.ti -1c
.RI "const \fBGOOGLE_API_KEY\fP 'AIzaSyCPUwTRKp-Nc6Fe3CKttxQvKXg-yHBQrXI'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const DB_DATABASE 'kd268'"

.PP
Definition at line 10 of file config\&.php\&.
.SS "const DB_HOST 'acadgpl\&.ucc\&.nau\&.edu'"
Database config variables 
.PP
Definition at line 7 of file config\&.php\&.
.SS "const DB_PASSWORD 'capstone'"

.PP
Definition at line 9 of file config\&.php\&.
.SS "const DB_USER 'kd268'"

.PP
Definition at line 8 of file config\&.php\&.
.SS "const GOOGLE_API_KEY 'AIzaSyCPUwTRKp-Nc6Fe3CKttxQvKXg-yHBQrXI'"

.PP
Definition at line 15 of file config\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
