.TH "Website/databaseConfig.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/databaseConfig.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$dbV\fP = new \fBdbValidator\fP()"
.br
.ti -1c
.RI "\fB$host\fP = 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$dbV = new \fBdbValidator\fP()"

.PP
Definition at line 5 of file databaseConfig\&.php\&.
.SS "$host = 'acadgpl\&.ucc\&.nau\&.edu'"

.PP
Definition at line 15 of file databaseConfig\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
