.TH "DB_Connect" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Connect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP ()"
.br
.ti -1c
.RI "\fBclose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file db_connect\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
