.TH "DB_Functions" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_Functions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstoreUser\fP ($name, $email, $gcm_regid)"
.br
.ti -1c
.RI "\fBgetUserByEmail\fP ($email)"
.br
.ti -1c
.RI "\fBgetAllUsers\fP ()"
.br
.ti -1c
.RI "\fBisUserExisted\fP ($email)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file db_functions\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getAllUsers ()"
Getting all users 
.PP
Definition at line 55 of file db_functions\&.php\&.
.SS "getUserByEmail ($email)"
Get user by email and password 
.PP
Definition at line 47 of file db_functions\&.php\&.
.SS "isUserExisted ($email)"
Check user is existed or not 
.PP
Definition at line 63 of file db_functions\&.php\&.
.SS "storeUser ($name, $email, $gcm_regid)"
Storing new user returns user details 
.PP
Definition at line 25 of file db_functions\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
