.TH "DetailViewController()" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetailViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) - \fBconfigureView\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "UIPopoverController * \fBmasterPopoverController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file DetailViewController\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
