.TH "GCM" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GCM \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsend_notification\fP ($registatoin_ids, $message)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description of \fBGCM\fP
.PP
\fBAuthor:\fP
.RS 4
Ravi Tamada 
.RE
.PP

.PP
Definition at line 13 of file GCM\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "send_notification ($registatoin_ids, $message)"
Sending Push Notification 
.PP
Definition at line 24 of file GCM\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
