.TH "HomeViewController" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(IBAction) - \fBlocalizationButtonPressed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file HomeViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
