.TH "Website/index.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/index.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!$_SESSION['user']) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (!$_SESSION['user']) else"
\fBInitial value:\fP
.PP
.nf
{
                include 'menuFunction\&.php'
.fi
.PP
Definition at line 67 of file index\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
