.TH "iPhone/CurrentAddress/main.m" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iPhone/CurrentAddress/main.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 51 of file main\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
