.TH "MainMenu" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenu \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIView\&.
.SH "Detailed Description"
.PP 
Definition at line 11 of file MainMenu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
