.TH "Map2" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map2 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet MKMapView * \fBmapView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file Map2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
