.TH "MapViewController" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController, <MKMapViewDelegate>, and <MKReverseGeocoderDelegate>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(IBAction) - \fBreverseGeocodeCurrentLocation\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "MKMapView * \fBmapView\fP"
.br
.ti -1c
.RI "UIBarButtonItem * \fBgetAddressButton\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet MKMapView * \fBmapView\fP"
.br
.ti -1c
.RI "MKReverseGeocoder * \fBreverseGeocoder\fP"
.br
.ti -1c
.RI "IBOutlet UIBarButtonItem * \fBgetAddressButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file MapViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
