.TH "MasterViewController" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UITableViewController\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDetailViewController\fP * \fBdetailViewController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file MasterViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
