.TH "MasterViewController()" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterViewController() \- 
.SH SYNOPSIS
.br
.PP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "NSMutableArray * \fB_objects\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file MasterViewController\&.m\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
