.TH "Website/MCMcreateNewAccount.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/MCMcreateNewAccount.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$_SESSION\fP ['user'] = 'guestOfKimi'"
.br
.ti -1c
.RI "\fB$fields\fP"
.br
.ti -1c
.RI "\fB$months\fP"
.br
.ti -1c
.RI "\fBforeach\fP ($fields as $field=> $label)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$_SESSION['user'] = 'guestOfKimi'"

.PP
Definition at line 59 of file MCMcreateNewAccount\&.php\&.
.SS "$fields"
\fBInitial value:\fP
.PP
.nf
= array('userName' => 'User Name: ',
                        'pwd' => 'Password: ',
                        'pwdConfirmation' => 'Confirm Password: ',
                        'firstName' => 'First Name: ',
                        'lastName' => 'Last Name: ',
                        'email' => 'E-Mail: ',
                        'bDay' => 'Birthday -> Day: ',
                        'bDayMonth' => 'Month: ',
                        'bDayYear' => 'Year: ',
                        'student' => 'Student?',
                        'gender' => 'Gender? ')
.fi
.PP
Definition at line 60 of file MCMcreateNewAccount\&.php\&.
.SS "$months"
\fBInitial value:\fP
.PP
.nf
= array('1' => 'Jan',
                        '2' => 'Feb',
                        '3' => 'Mar',
                        '4' => 'Apr',
                        '5' => 'May',
                        '6' => 'Jun',
                        '7' => 'Jul',
                        '8' => 'Aug',
                        '9' => 'Sep',
                        '10' => 'Oct',
                        '11' => 'Nov',
                        '12' => 'Dec')
.fi
.PP
Definition at line 72 of file MCMcreateNewAccount\&.php\&.
.SS "foreach($fields as $field=> $label)"

.PP
Definition at line 86 of file MCMcreateNewAccount\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
