.TH "Website/MCMhomePage.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/MCMhomePage.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP ($_SESSION['user']==='guestOfKimi'||!$_SESSION['user']) header('Location"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "if($_SESSION['user']==='guestOfKimi'||!$_SESSION['user']) header('Location"

.PP
Definition at line 58 of file MCMhomePage\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
