.TH "Website/MCMlogin.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/MCMlogin.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$fields\fP"
.br
.ti -1c
.RI "\fBforeach\fP ($fields as $field=> $label)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$fields"
\fBInitial value:\fP
.PP
.nf
= array('userName' => 'Your User Name:',
                    'pwd' => 'Your Password:')
.fi
.PP
Definition at line 62 of file MCMlogin\&.php\&.
.SS "foreach($fields as $field=> $label)"

.PP
Definition at line 66 of file MCMlogin\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
