.TH "Website/menuFunction.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/menuFunction.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdisplayMenu\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "displayMenu ()"

.PP
Definition at line 3 of file menuFunction\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
