.TH "Website/PHPGetNearbyMerchants.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/PHPGetNearbyMerchants.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$databasehost\fP = 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.ti -1c
.RI "\fB$databasename\fP = 'kd268'"
.br
.ti -1c
.RI "\fB$databaseusername\fP ='kd268'"
.br
.ti -1c
.RI "\fB$databasepassword\fP = 'capstone'"
.br
.ti -1c
.RI "\fB$currentUser\fP = 'chihi'"
.br
.ti -1c
.RI "\fB$currentLon\fP = 0"
.br
.ti -1c
.RI "\fB$currentLat\fP = 0"
.br
.ti -1c
.RI "\fB$pi2\fP = pi()/2\&.0"
.br
.ti -1c
.RI "\fB$mil\fP = 1000000\&.0"
.br
.ti -1c
.RI "\fB$con\fP"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$res\fP = mysql_query($query)"
.br
.ti -1c
.RI "\fBif\fP(!$res) \fBelse\fP"
.br
.ti -1c
.RI "\fB$sth\fP = mysql_query($query)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$con"
\fBInitial value:\fP
.PP
.nf
= mysql_connect($databasehost,$databaseusername,$databasepassword) 
        or die(mysql_error())
.fi
.PP
Definition at line 14 of file PHPGetNearbyMerchants\&.php\&.
.SS "$currentLat = 0"

.PP
Definition at line 9 of file PHPGetNearbyMerchants\&.php\&.
.SS "$currentLon = 0"

.PP
Definition at line 8 of file PHPGetNearbyMerchants\&.php\&.
.SS "$currentUser = 'chihi'"

.PP
Definition at line 7 of file PHPGetNearbyMerchants\&.php\&.
.SS "$databasehost = 'acadgpl\&.ucc\&.nau\&.edu'"

.PP
Definition at line 3 of file PHPGetNearbyMerchants\&.php\&.
.SS "$databasename = 'kd268'"

.PP
Definition at line 4 of file PHPGetNearbyMerchants\&.php\&.
.SS "$databasepassword = 'capstone'"

.PP
Definition at line 6 of file PHPGetNearbyMerchants\&.php\&.
.SS "$databaseusername ='kd268'"

.PP
Definition at line 5 of file PHPGetNearbyMerchants\&.php\&.
.SS "$mil = 1000000\&.0"

.PP
Definition at line 11 of file PHPGetNearbyMerchants\&.php\&.
.SS "$pi2 = pi()/2\&.0"

.PP
Definition at line 10 of file PHPGetNearbyMerchants\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
= 'SELECT currentLat, currentLon FROM kd268\&.customers WHERE '\&.
        'userName = '$currentUser''
.fi
.PP
Definition at line 19 of file PHPGetNearbyMerchants\&.php\&.
.SS "$res = mysql_query($query)"

.PP
Definition at line 21 of file PHPGetNearbyMerchants\&.php\&.
.SS "$sth = mysql_query($query)"

.PP
Definition at line 36 of file PHPGetNearbyMerchants\&.php\&.
.SS "\fBif\fP (mysql_errno()) else"
\fBInitial value:\fP
.PP
.nf
{
    $currentLon = mysql_result($res, 0, 'currentLon')/$mil
.fi
.PP
Definition at line 24 of file PHPGetNearbyMerchants\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
