.TH "Website/PHPPut.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/PHPPut.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$json\fP = file_get_contents('php://input')"
.br
.ti -1c
.RI "\fB$obj\fP = json_decode($json)"
.br
.ti -1c
.RI "\fB$con\fP"
.br
.ti -1c
.RI "\fB$posts\fP = array(1)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$con"
\fBInitial value:\fP
.PP
.nf
= mysql_connect('acadgpl\&.ucc\&.nau\&.edu', 'kd268', 'capstone')
        or die('Cannot connect to the DB')
.fi
.PP
Definition at line 8 of file PHPPut\&.php\&.
.SS "$json = file_get_contents('php://input')"

.PP
Definition at line 4 of file PHPPut\&.php\&.
.SS "$obj = json_decode($json)"

.PP
Definition at line 5 of file PHPPut\&.php\&.
.SS "$posts = array(1)"

.PP
Definition at line 20 of file PHPPut\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
