.TH "Website/PHPQuery.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/PHPQuery.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$userName\fP = 'chihi'"
.br
.ti -1c
.RI "\fB$databasehost\fP = 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.ti -1c
.RI "\fB$databasename\fP = 'kd268'"
.br
.ti -1c
.RI "\fB$databaseusername\fP ='kd268'"
.br
.ti -1c
.RI "\fB$databasepassword\fP = 'capstone'"
.br
.ti -1c
.RI "\fB$json\fP = file_get_contents('php://input')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$databasehost = 'acadgpl\&.ucc\&.nau\&.edu'"

.PP
Definition at line 5 of file PHPQuery\&.php\&.
.SS "$databasename = 'kd268'"

.PP
Definition at line 6 of file PHPQuery\&.php\&.
.SS "$databasepassword = 'capstone'"

.PP
Definition at line 8 of file PHPQuery\&.php\&.
.SS "$databaseusername ='kd268'"

.PP
Definition at line 7 of file PHPQuery\&.php\&.
.SS "$json = file_get_contents('php://input')"

.PP
Definition at line 10 of file PHPQuery\&.php\&.
.SS "$userName = 'chihi'"

.PP
Definition at line 3 of file PHPQuery\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
