.TH "Website/PHPRetrieveUserNotification.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/PHPRetrieveUserNotification.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$databasehost\fP = 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.ti -1c
.RI "\fB$databasename\fP = 'kd268'"
.br
.ti -1c
.RI "\fB$databaseusername\fP ='kd268'"
.br
.ti -1c
.RI "\fB$databasepassword\fP = 'capstone'"
.br
.ti -1c
.RI "\fB$currentUser\fP = 'kimi'"
.br
.ti -1c
.RI "\fB$con\fP"
.br
.ti -1c
.RI "\fB$query\fP"
.br
.ti -1c
.RI "\fB$res\fP = mysql_query($query)"
.br
.ti -1c
.RI "\fBif\fP(mysql_errno()) \fBelse\fP"
.br
.ti -1c
.RI "\fBwhile\fP ($r=mysql_fetch_assoc($res))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$con"
\fBInitial value:\fP
.PP
.nf
= mysql_connect($databasehost,$databaseusername,$databasepassword) 
        or die(mysql_error())
.fi
.PP
Definition at line 10 of file PHPRetrieveUserNotification\&.php\&.
.SS "$currentUser = 'kimi'"

.PP
Definition at line 7 of file PHPRetrieveUserNotification\&.php\&.
.SS "$databasehost = 'acadgpl\&.ucc\&.nau\&.edu'"

.PP
Definition at line 3 of file PHPRetrieveUserNotification\&.php\&.
.SS "$databasename = 'kd268'"

.PP
Definition at line 4 of file PHPRetrieveUserNotification\&.php\&.
.SS "$databasepassword = 'capstone'"

.PP
Definition at line 6 of file PHPRetrieveUserNotification\&.php\&.
.SS "$databaseusername ='kd268'"

.PP
Definition at line 5 of file PHPRetrieveUserNotification\&.php\&.
.SS "$query"
\fBInitial value:\fP
.PP
.nf
= 'SELECT charged, timestamp FROM kd268\&.customers WHERE ' \&. 
        'userName = '$currentUser''
.fi
.PP
Definition at line 15 of file PHPRetrieveUserNotification\&.php\&.
.SS "$res = mysql_query($query)"

.PP
Definition at line 19 of file PHPRetrieveUserNotification\&.php\&.
.SS "\fBif\fP (mysql_errno()) else"
\fBInitial value:\fP
.PP
.nf
{
    $rows = array()
.fi
.PP
Definition at line 27 of file PHPRetrieveUserNotification\&.php\&.
.SS "while($r=mysql_fetch_assoc($res))"

.PP
Definition at line 29 of file PHPRetrieveUserNotification\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
