.TH "Website/PHPValidateLogin.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/PHPValidateLogin.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$databasehost\fP = 'acadgpl\&.ucc\&.nau\&.edu'"
.br
.ti -1c
.RI "\fB$databasename\fP = 'kd268'"
.br
.ti -1c
.RI "\fB$databaseusername\fP ='kd268'"
.br
.ti -1c
.RI "\fB$databasepassword\fP = 'capstone'"
.br
.ti -1c
.RI "\fB$json\fP = file_get_contents('php://input')"
.br
.ti -1c
.RI "\fB$obj\fP = json_decode($json)"
.br
.ti -1c
.RI "\fB$con\fP"
.br
.ti -1c
.RI "\fBif\fP($obj->{'customer'}== '1') \fBelse\fP"
.br
.ti -1c
.RI "\fB$res\fP = mysql_query($query)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$con"
\fBInitial value:\fP
.PP
.nf
= mysql_connect($databasehost,$databaseusername,$databasepassword) 
        or die(mysql_error())
.fi
.PP
Definition at line 13 of file PHPValidateLogin\&.php\&.
.SS "$databasehost = 'acadgpl\&.ucc\&.nau\&.edu'"

.PP
Definition at line 3 of file PHPValidateLogin\&.php\&.
.SS "$databasename = 'kd268'"

.PP
Definition at line 4 of file PHPValidateLogin\&.php\&.
.SS "$databasepassword = 'capstone'"

.PP
Definition at line 6 of file PHPValidateLogin\&.php\&.
.SS "$databaseusername ='kd268'"

.PP
Definition at line 5 of file PHPValidateLogin\&.php\&.
.SS "$json = file_get_contents('php://input')"

.PP
Definition at line 8 of file PHPValidateLogin\&.php\&.
.SS "$obj = json_decode($json)"

.PP
Definition at line 10 of file PHPValidateLogin\&.php\&.
.SS "$res = mysql_query($query)"

.PP
Definition at line 27 of file PHPValidateLogin\&.php\&.
.SS "\fBif\fP (mysql_num_rows($res)< 1) else"
\fBInitial value:\fP
.PP
.nf
{
    $query = 'SELECT * FROM kd268\&.merchants WHERE userName = '' \&. $obj->{'userName'} \&.
            '' AND pwd = ''\&. $obj->{'pwd'} \&. '''
.fi
.PP
Definition at line 21 of file PHPValidateLogin\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
