.TH "PlacemarkViewController" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlacemarkViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIViewController, <UITableViewDelegate>, and <UITableViewDataSource>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(IBAction) - \fBdone\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "UITableView * \fBtableView\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MKPlacemark * \fBplacemark\fP"
.br
.ti -1c
.RI "IBOutlet UITableView * \fBtableView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file PlacemarkViewController\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
