.TH "Andriod/MerchantActivity/gen/app/merchantLocalization/R.java" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Andriod/MerchantActivity/gen/app/merchantLocalization/R.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBR\fP"
.br
.ti -1c
.RI "class \fBR\&.attr\fP"
.br
.ti -1c
.RI "class \fBR\&.drawable\fP"
.br
.ti -1c
.RI "class \fBR\&.id\fP"
.br
.ti -1c
.RI "class \fBR\&.layout\fP"
.br
.ti -1c
.RI "class \fBR\&.menu\fP"
.br
.ti -1c
.RI "class \fBR\&.string\fP"
.br
.ti -1c
.RI "class \fBR\&.style\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBapp\&.merchantLocalization\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
