.TH "Website/cloudMessaging/register.php" 3 "Thu Feb 21 2013" "Version 01" "MCMProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Website/cloudMessaging/register.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$json\fP = array()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$json = array()"

.PP
Definition at line 4 of file register\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MCMProject from the source code\&.
